config/routes.rb
Rails.application.routes.draw do

  namespace :api do

    resources :links

  end

  root 'links#index'
  get "/:short_url", to: "links#show", as: :releted_link
  get "compressed/:short_url", to: "links#compressed", as: :shortened
  resources :links #, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/link.rb
class Link < ApplicationRecord

  validates         :original_url,
                    presence: { message: I18n.t('custom_errors.original_url.presence')},
                    on: :create

  validates         :original_url,
                    url: { message: I18n.t('custom_errors.original_url.url')}

  validates         :custom_url,
                    uniqueness: { message: I18n.t('custom_errors.custom_url') },
                    if: 'custom_url.present?',
                    on: :create

  validates         :sanitized_url,
                    uniqueness: { message: I18n.t('custom_errors.sanitized_url') },
                    unless: 'custom_url.present?'

  validate          :custom_url_exist?,
                    if: 'custom_url.present?'

  validate          :http_status_valid?

  before_create     :generate_short_url

  before_validation :get_http_status, :sanitize

  def http_status_valid?
    errors.add(:http_status, I18n.t('custom_errors.http_status_valid', status: http_status)) if http_status > 403
  end

  def get_http_status
    url = Faraday.get(original_url)
    self.http_status = url.status
  end

  def custom_url_exist?
    errors.add(:custom_url, I18n.t('custom_errors.custom_url_exist')) if Link.where(short_url: custom_url).present?
  end

  def generate_short_url
    if custom_url.present?
      self.short_url = custom_url
    else
      chars = ['0'..'9','A'..'Z','a'..'z'].map{|range| range.to_a}.flatten
      self.short_url = 6.times.map{chars.sample}.join
      self.short_url = 6.times.map{chars.sample}.join until Link.find_by_short_url(short_url).nil?
    end
  end

  def sanitize
    self.original_url.strip!
    self.sanitized_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
    self.sanitized_url.slice!(-1) if sanitized_url[-1] == "/"
    self.sanitized_url = "http://#{sanitized_url}"
  end

end

app/controllers/api/application_controller.rb
class Api::ApplicationController < InheritedResources::Base

  protect_from_forgery with: :null_session, if: ->{request.format.json?}

  respond_to :json

end

app/controllers/api/links_controller.rb
class Api::LinksController < Api::ApplicationController

  def create
    if link_params[:custom_url].present?
      @link = Link.new(link_params{original_url})
      @link.save
    else
      @link = Link.find_or_create_by(link_params)
    end
    create! do |success, failure|
      success.json do
        render  json: @link, serializer: LinkSerializer
      end
    end
  end

  private

  def link_params
    params.require(:link).permit(:original_url, :custom_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base; end

app/controllers/links_controller.rb
class LinksController < InheritedResources::Base

  before_action :find_url, only: [:show, :compressed]

  respond_to :js, :html

  def index
    @link = Link.new
  end

  def show
    redirect_to @link.sanitized_url
  end

  def create

    if link_params[:custom_url].present?
      @link = Link.new(link_params{original_url})
      @link.save
    else
      @link = Link.find_or_create_by(link_params)
    end
    respond_with(@link) do |success, failure|
      success.js {render layout: false}
    end
  end

  private

    def find_url
      @link       = Link.find_by(short_url:     params[:short_url])
    end

    def link_params
      params.require(:link).permit(:original_url, :custom_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/views/layouts/application.haml
!!!
%html
  = render({ partial: 'layouts/partials/head'})
  %body
    = render({ partial: 'layouts/partials/header'})
    = yield

app/views/layouts/partials/_footer.haml
%footer
  .col-md-10.col-md-offset-1
    %p.text-center

app/views/layouts/partials/_head.haml
%head
  %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
  %title CutUrl

  = csrf_meta_tags

  = stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload', media: 'all'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/partials/_header.haml
%header
  %nav.navbar.navbar-fixed-top.navbar-inverse
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{'aria-controls': 'navbar', 'aria-expanded': 'false', 'data-target': '#navbar', 'data-toggle': 'collapse'}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to('Cut URL', root_url, class: 'navbar-brand')

app/views/links/compressed.haml
.container
  .form-card.text-center
    %h3 Well done, your link has been shortened!
    %h3 Share it now!
    .col-md-6.col-md-offset-3
      .form-group.string.disabled
        %label.string.disabled.control-label{for: 'url_original_url'}  Your original URL was:
        %input#url_original_url.string.disabled.form-control{disabled: 'disabled', value: "#{@link.original_url}"}
      %br
      %p.larger
        Your compressed URL is: &nbsp;
        %span#short-url{data: {container: 'body', toggle: 'popover', content: 'Press Ctrl-C to copy', placement: 'top'}}= "#{request.base_url}/#{@link.short_url}"
      = link_to 'Compress new link', root_path, class: 'btn btn-success'

app/views/links/create.js.erb
<% if @exist_link.present? %>
  toastr.info(<% I18n.t('remote.link.info')%>);
  setTimeout(function() {
      window.location.href = '<%= shortened_path(@exist_link.short_url) %>';
  }, 1500);
<% else %>
  <% if @link.errors.present? %>
    toastr.error('<%= @link.errors.full_messages.first %>');
  <% else %>
    toastr.success(<% I18n.t('remote.link.success')%>);
    setTimeout(function() {
        window.location.href = '<%= shortened_path(@link.short_url) %>';
    }, 1100);
  <% end %>
<% end %>

app/views/links/index.haml
.container
  .col-md-6.col-md-offset-3
    .main-card
      %h2.text-center Compress your links!
      %h4.text-center A simple URL shortener.
      = simple_form_for @link, remote: true, html: { class: 'text-center' } do |f|
        = f.input :original_url, as: :string, placeholder: t('forms.link.placeholders.original_url'), label: false
        = f.input :custom_url,   as: :string, placeholder: t('forms.link.placeholders.custom_url'), label: false
        = f.submit 'Compress!', class: 'btn btn-danger'